#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Start pushing"

git push origin master

echo "Successful pushing"

echo "Deploy starting"

ssh test "cd /home/app/express-tasks && git reset --hard HEAD && git pull && chmod +x run.sh run-migrate.sh"

scp .env test:/home/app/express-tasks

ssh test "cd /home/app/express-tasks && ./run.sh"
